In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("/home/liyy/0.software/Strinit/StrinitPy/test0908/putative_bc.csv")

In [77]:
df.shape[0]

3176234

In [20]:
# 1. putative_umi为空的行数和比例
mask_empty_umi = df["putative_umi"].isna()
empty_umi_count = mask_empty_umi.sum()
empty_umi_ratio = empty_umi_count / df.shape[0]

# 2. putative_umi为空的行中，putative_bc含有"GGAGG"
mask_bc_GGAGG = mask_empty_umi & df["putative_bc"].str.contains("GGAGG")
GGAGG_count = mask_bc_GGAGG.sum()
GGAGG_ratio = GGAGG_count / df.shape[0]

# 3. putative_umi为空的行中，putative_bc里"A"比例 > 50%
def A_ratio(seq):
    return seq.count("A") / len(seq) if seq and len(seq) > 0 else 0

mask_high_A = mask_empty_umi & df["putative_bc"].apply(A_ratio).gt(0.5)
high_A_count = mask_high_A.sum()
high_A_ratio = high_A_count / df.shape[0]

### 
mask_bc_GGAGG_2 = mask_empty_umi & df["putative_bc"].str.contains("GGA|GAG|AGG", na=False)
high_A_count_2 = mask_bc_GGAGG_2.sum()
high_A_ratio_2 = high_A_count_2 / df.shape[0]

empty_umi_count, empty_umi_ratio, GGAGG_count, GGAGG_ratio, high_A_count, high_A_ratio, high_A_count_2, high_A_ratio_2

(np.int64(899456),
 np.float64(0.28318316597580656),
 np.int64(53418),
 np.float64(0.016818030409598284),
 np.int64(252486),
 np.float64(0.0794922540341801),
 np.int64(652166),
 np.float64(0.20532681156363164))

In [19]:
df[mask_bc_GGAGG_2]

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts
0,250F302306011_11_189_10128_196076064_11010_0_1...,GCACCGGACGGGAAGGCCGTGCAGAA,-16,6.0,NaN,NaN,NaN,NaN
1,250F302306011_11_7526_9970_192395919_21242_3_1...,CGATTGATATGGAAGGCAATCTACTC,-16,15.0,NaN,NaN,NaN,NaN
2,250F302306011_13_5384_14012_225141126_12157_1_...,GAATCCTAGCGGAAGGTGGTACTGAC,-16,8.0,NaN,NaN,NaN,NaN
9,250F302306011_13_5076_9972_221463097_28471_2_1...,ACGGTCTTGCGAAGCGAATTTGGACT,-1,NaN,NaN,NaN,NaN,NaN
14,250F302306011_11_30_10584_196078056_13791_3_14.11,GCCTACGAAGAGAAGGGAGGACGGAA,-1,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
3176193,250F302306011_13_6977_11326_232495484_7557_2_1...,GCTTAATCCAGGAAGGAGGTACCTGC,-20,6.0,NaN,NaN,NaN,NaN
3176210,250F302306011_12_7069_11498_199147382_9286_1_1...,TGCGACGATGGAAAGGATAGCCTCGT,-1,NaN,NaN,NaN,NaN,NaN
3176220,250F302306011_12_7507_11205_198828148_12600_0_...,AGCAATTAAGCGAAGGACCGGTCAAG,-1,NaN,NaN,NaN,NaN,NaN
3176222,250F302306011_12_6547_10610_205171205_15031_2_...,CGCACAGCGGGGAAGGCACCTTACTG,-16,12.0,NaN,NaN,NaN,NaN
3176226,250F302306011_13_6884_11369_232918250_15133_3_...,CGGTCTGTTCGGAAGGAGCGTGTTGC,-16,6.0,NaN,NaN,NaN,NaN

In [21]:
empty_count = df["putative_bc"].isna().sum() + (df["putative_bc"] == "").sum()
empty_count

np.int64(0)

In [22]:
big_df = pd.read_csv("/home/liyy/0.software/Strinit/StrinitPy/test0908/corrected_bc.csv")

In [30]:
big_df.shape

(3176234, 10)

## 统计BC_corrected不为空，但是umi为空

In [24]:
count = big_df[(big_df["BC_corrected"].notna()) & (big_df["BC_corrected"] != "") &
           (big_df["putative_umi"].isna() | (big_df["putative_umi"] == ""))].shape[0]

print("putative_bc 不为空但 putative_umi 为空的行数:", count)

putative_bc 不为空但 putative_umi 为空的行数: 366530

## 统计BC_corrected为空，umi也为空

In [26]:
# 条件：BC_corrected 为空 & putative_umi 为空
count = big_df[((big_df["BC_corrected"].isna()) | (big_df["BC_corrected"] == "")) &
           ((big_df["putative_umi"].isna()) | (big_df["putative_umi"] == ""))].shape[0]

print("BC_corrected 和 putative_umi 都为空的行数:", count)

BC_corrected 和 putative_umi 都为空的行数: 532926

## 统计BC_corrected为空，umi不为空的比例

In [31]:
mask = ((big_df["BC_corrected"].isna()) | (big_df["BC_corrected"] == "")) & \
       (big_df["putative_umi"].notna()) & (big_df["putative_umi"] != "")

count = big_df[mask].shape[0]


print("BC_corrected 为空且 putative_umi 不为空的行数:", count)

BC_corrected 为空且 putative_umi 不为空的行数: 419419

## 统计BC_corrected不为空，umi也不为空 （matched）

In [29]:
# 条件：BC_corrected 非空 & putative_umi 非空
count = big_df[(big_df["BC_corrected"].notna()) & (big_df["BC_corrected"] != "") &
           (big_df["putative_umi"].notna()) & (big_df["putative_umi"] != "")].shape[0]

print("BC_corrected 和 putative_umi 都不为空的行数:", count)

BC_corrected 和 putative_umi 都不为空的行数: 1857359

In [32]:
big_df

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,BC_corrected,strand
0,250F302306011_11_189_10128_196076064_11010_0_1...,GCACCGGACGGGAAGGCCGTGCAGAA,-16,6.0,NaN,NaN,NaN,NaN,CACCGGACGGGGAAGGCCGTGCAGAA,+
1,250F302306011_11_7526_9970_192395919_21242_3_1...,CGATTGATATGGAAGGCAATCTACTC,-16,15.0,NaN,NaN,NaN,NaN,CGATTGATATGGAAGGCAATCTACTC,+
2,250F302306011_13_5384_14012_225141126_12157_1_...,GAATCCTAGCGGAAGGTGGTACTGAC,-16,8.0,NaN,NaN,NaN,NaN,AACTTCTAGCGGAAGGTGGTACTGAC,+
3,250F302306011_11_151_6689_196071554_18096_3_14.53,TATGACAAGCGGAAGGGTATCTTGCA,-16,13.0,ATGCCTCCATCATCG,-31.0,AAAAA,-88.0,TATGACAAGCGGAAGGGTATCTTGCA,+
4,250F302306011_11_192_9886_196073109_13496_1_16.26,TTGGAATCGGGGAAGGTGGCGAACGT,-16,25.0,ATAGGCTCAACATCG,-31.0,AAAAA,-81.0,NaN,+
...,...,...,...,...,...,...,...,...,...,...
3176229,250F302306011_13_4306_7964_220076051_14384_1_1...,CATGACTTATGGAAGGCTTTCATAC,-15,7.0,CTCGAAATGACATCG,-30.0,AAAAA,-74.0,CATGACTTATGGAAGGCTTCATATAC,+
3176230,250F302306011_13_4327_12631_220070647_20353_1_...,GAGCGGACCGGGAAGGTCCACCTCGT,-16,15.0,AGAGGGCCACCATCG,-31.0,AAAAA,-81.0,GAGCGGACCGGGAAGGTCCACCTCGT,+
3176231,250F302306011_14_5389_13498_240964337_12830_1_...,AGAGTGTCGGGGAAGGCCGCAGAA,-14,9.0,AGAGTAGGTACATCG,-29.0,AAAAA,-57.0,NaN,+
3176232,250F302306011_13_4275_10946_220075964_15924_3_...,CGCGAACGGCGGAAGGTATTCCACGT,-17,4.0,ATTTCATGACCATCG,-35.0,AAAAA,-60.0,NaN,+
3176233,250F302306011_13_5837_14173_220426086_50586_0_...,TTCGCCTGACGGAAGGGGCTTCCAGG,-17,8.0,TAGTAGGAAGCATCG,-32.0,AAATA,-60.0,TTCGCCTGACGGAAGGGCTTCCAGGC,+

In [37]:
cond1 = (big_df["putative_bc"].notna()) & (big_df["putative_bc"] != "") & ((big_df["BC_corrected"].isna()) | (big_df["BC_corrected"] == ""))
count1 = big_df[cond1].shape[0]

# 2. putative_bc 有值 & BC_corrected 有值 & 二者不一致
cond2 = (big_df["putative_bc"].notna()) & (big_df["putative_bc"] != "") & (big_df["BC_corrected"].notna()) & (big_df["BC_corrected"] != "") & (big_df["putative_bc"] != big_df["BC_corrected"])
count2 = big_df[cond2].shape[0]

print("putative_bc 有值但 BC_corrected 没值的行数:", count1)
print("putative_bc 和 BC_corrected 都有值但不一致的行数:", count2)

putative_bc 有值但 BC_corrected 没值的行数: 952345
putative_bc 和 BC_corrected 都有值但不一致的行数: 877451

In [42]:
big_df_corrected = big_df[cond2]

In [41]:
GCACCGGACGGGAAGGCCGTGCAGAA
CACCGGACGGGGAAGGCCGTGCAGAA

NameError: name 'GCACCGGACGGGAAGGCCGTGCAGAA' is not defined

In [43]:
big_df_corrected

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,BC_corrected,strand
0,250F302306011_11_189_10128_196076064_11010_0_1...,GCACCGGACGGGAAGGCCGTGCAGAA,-16,6.0,NaN,NaN,NaN,NaN,CACCGGACGGGGAAGGCCGTGCAGAA,+
2,250F302306011_13_5384_14012_225141126_12157_1_...,GAATCCTAGCGGAAGGTGGTACTGAC,-16,8.0,NaN,NaN,NaN,NaN,AACTTCTAGCGGAAGGTGGTACTGAC,+
6,250F302306011_11_200_8171_196073922_14576_3_15.25,CAGTCTGTGGGGAAGGCACATTCTTC,-16,22.0,AAGACCCACACATCG,-31.0,AAAAA,-59.0,CAGTCTGCGGGGAAGGCACATTCTTC,+
7,250F302306011_11_245_10520_196072701_14000_0_1...,TGAGTGAACTGGAAGGCGGAGACCG,-15,8.0,TAACATTGGACATCG,-30.0,AAAAA,-56.0,TGAGTGAACTGGAAGGCGGAGACCGG,+
11,250F302306011_11_214_9508_196064655_22764_3_13.48,AGCCGCTAATGGAAGGTCGTTGGAC,-15,8.0,ACGTGAGCACCATCG,-30.0,AAAAA,-59.0,AGCCGCTAATGGAAGGTCGTCTGGAC,+
...,...,...,...,...,...,...,...,...,...,...
3176222,250F302306011_12_6547_10610_205171205_15031_2_...,CGCACAGCGGGGAAGGCACCTTACTG,-16,12.0,NaN,NaN,NaN,NaN,CACAGCGTGGGGAAGGCACCTTACTG,+
3176223,250F302306011_12_5914_12148_212429908_11378_0_...,CTGCGACGATGGAAGGGATGTGGTAA,-17,9.0,CAGAAAAATCCATCG,-32.0,AAAAA,-63.0,CTGCGACGATGGAAGGATGTGGTAAC,+
3176226,250F302306011_13_6884_11369_232918250_15133_3_...,CGGTCTGTTCGGAAGGAGCGTGTTGC,-16,6.0,NaN,NaN,NaN,NaN,GTCTGTCTTCGGAAGGAGCGTGTTGC,+
3176229,250F302306011_13_4306_7964_220076051_14384_1_1...,CATGACTTATGGAAGGCTTTCATAC,-15,7.0,CTCGAAATGACATCG,-30.0,AAAAA,-74.0,CATGACTTATGGAAGGCTTCATATAC,+
3176233,250F302306011_13_5837_14173_220426086_50586_0_...,TTCGCCTGACGGAAGGGGCTTCCAGG,-17,8.0,TAGTAGGAAGCATCG,-32.0,AAATA,-60.0,TTCGCCTGACGGAAGGGCTTCCAGGC,+

In [45]:
count = big_df_corrected[(big_df_corrected["BC_corrected"].notna()) & (big_df_corrected["BC_corrected"] != "") &
           (big_df_corrected["putative_umi"].isna() | (big_df_corrected["putative_umi"] == ""))].shape[0]

print("putative_bc 不为空但 putative_umi 为空的行数:", count)

putative_bc 不为空但 putative_umi 为空的行数: 314310

In [47]:
big_df_corrected[(big_df_corrected["BC_corrected"].notna()) & (big_df_corrected["BC_corrected"] != "") &
           (big_df_corrected["putative_umi"].isna() | (big_df_corrected["putative_umi"] == ""))]

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,BC_corrected,strand
0,250F302306011_11_189_10128_196076064_11010_0_1...,GCACCGGACGGGAAGGCCGTGCAGAA,-16,6.0,NaN,NaN,NaN,NaN,CACCGGACGGGGAAGGCCGTGCAGAA,+
2,250F302306011_13_5384_14012_225141126_12157_1_...,GAATCCTAGCGGAAGGTGGTACTGAC,-16,8.0,NaN,NaN,NaN,NaN,AACTTCTAGCGGAAGGTGGTACTGAC,+
14,250F302306011_11_30_10584_196078056_13791_3_14.11,GCCTACGAAGAGAAGGGAGGACGGAA,-1,NaN,NaN,NaN,NaN,NaN,GTGCTACGAAGGAAGGGAGGACGGAA,+
37,250F302306011_11_3_10064_196087408_14120_3_14.68,GTACGAAGAAGGAAGGATCGATGATG,-16,8.0,NaN,NaN,NaN,NaN,TACGAAGAAGGGAAGGATCGATGATG,+
40,250F302306011_13_4891_11570_232327542_13167_2_...,GTCTCCAAGAGGAAGGCTATCTCGAA,-16,6.0,NaN,NaN,NaN,NaN,GTCTCCAAGAGGAAGGTTATCTCGAA,+
...,...,...,...,...,...,...,...,...,...,...
3176193,250F302306011_13_6977_11326_232495484_7557_2_1...,GCTTAATCCAGGAAGGAGGTACCTGC,-20,6.0,NaN,NaN,NaN,NaN,CTTAATCCAGGGAAGGAGGTACCTAC,+
3176210,250F302306011_12_7069_11498_199147382_9286_1_1...,TGCGACGATGGAAAGGATAGCCTCGT,-1,NaN,NaN,NaN,NaN,NaN,CTGCGACGATGGAAGGATGGCCTCGT,+
3176220,250F302306011_12_7507_11205_198828148_12600_0_...,AGCAATTAAGCGAAGGACCGGTCAAG,-1,NaN,NaN,NaN,NaN,NaN,GAGCAATTAAGGAAGGACCGGTCAAG,+
3176222,250F302306011_12_6547_10610_205171205_15031_2_...,CGCACAGCGGGGAAGGCACCTTACTG,-16,12.0,NaN,NaN,NaN,NaN,CACAGCGTGGGGAAGGCACCTTACTG,+
3176226,250F302306011_13_6884_11369_232918250_15133_3_...,CGGTCTGTTCGGAAGGAGCGTGTTGC,-16,6.0,NaN,NaN,NaN,NaN,GTCTGTCTTCGGAAGGAGCGTGTTGC,+

In [ ]:
GCCTACGAAGAGAAGGGAGGACGGAA
GTGCTACGAAGGAAGGGAGGACGGAA

In [48]:
-1 + (-26)

-27

In [52]:
def polyA_trimming_idx_neg(seq, **kwargs):
    idx_abs = polyA_trimming_idx(seq, **kwargs)  # 用上面的绝对坐标函数
    if idx_abs is None:
        return None
    return idx_abs - len(seq)  # 负数：从末尾往前的偏移

In [55]:
def polyA_trimming_idx(seq, seed="AAAA", window=10, min_A=7, min_tail_len=8):
    """
    从 read 末端往前检测 polyA，返回 polyA 起始的绝对坐标（0-based）。
    若未检测到则返回 None。
    """
    s = seq.upper()
    anchor = s.rfind(seed)  # 最右侧 seed 的起点（绝对坐标）
    if anchor == -1:
        return None

    polyA_start = anchor  # 先把 polyA 起点放在 seed 起点
    i = anchor - 1        # 从 seed 之前的碱基开始，向左延伸

    while i >= 0:
        if s[i] == 'A':
            polyA_start = i
            i -= 1
            continue
        left = max(0, i - window + 1)
        if s[left:i+1].count('A') >= min_A:
            polyA_start = i
            i -= 1
            continue
        break

    # 确保 polyA 足够长
    if len(s) - polyA_start < min_tail_len:
        return None
    return polyA_start

In [59]:
test = "AAATGGTTGAAGAAGGATAAAAAAAAAAAAAAAAAAGGACCCTCAGCATCGCAC"

In [60]:
polyA_trimming_idx_neg(test)

-36

In [61]:
### 0910

In [63]:
test_csv = pd.read_csv("/home/liyy/0.software/Strinit/StrinitPy/Add_barcode_umi_amend/test0910/BC_corrected.csv")

In [64]:
test_csv

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,read_types,BC_corrected,strand
0,250F302306011_11_189_10128_196076064_11010_0_1...,GCACCGGACGGGAAGGCCGTGCAGAA,-16,6.0,AGGACCCTCAGCATC,NaN,AAAAA,-58.0,3,CACCGGACGGGGAAGGCCGTGCAGAA,+
1,250F302306011_11_7526_9970_192395919_21242_3_1...,CGATTGATATGGAAGGCAATCTACTC,-16,15.0,ACCATTATTGGCACG,NaN,AAAAA,-70.0,3,CGATTGATATGGAAGGCAATCTACTC,+
2,250F302306011_13_5384_14012_225141126_12157_1_...,GAATCCTAGCGGAAGGTGGTACTGAC,-16,8.0,AGGAATAGTAACATC,NaN,AAAAA,-60.0,3,AACTTCTAGCGGAAGGTGGTACTGAC,+
3,250F302306011_11_151_6689_196071554_18096_3_14.53,TATGACAAGCGGAAGGGTATCTTGCA,-16,13.0,ATGCCTCCATCATCG,-31.0,AAAAA,-88.0,1,TATGACAAGCGGAAGGGTATCTTGCA,+
4,250F302306011_11_192_9886_196073109_13496_1_16.26,TTGGAATCGGGGAAGGTGGCGAACGT,-16,25.0,ATAGGCTCAACATCG,-31.0,AAAAA,-81.0,1,NaN,+
...,...,...,...,...,...,...,...,...,...,...,...
3176229,250F302306011_13_4306_7964_220076051_14384_1_1...,CATGACTTATGGAAGGCTTTCATAC,-15,7.0,CTCGAAATGACATCG,-30.0,AAAAA,-74.0,12,CATGACTTATGGAAGGCTTCATATAC,+
3176230,250F302306011_13_4327_12631_220070647_20353_1_...,GAGCGGACCGGGAAGGTCCACCTCGT,-16,15.0,AGAGGGCCACCATCG,-31.0,AAAAA,-81.0,1,GAGCGGACCGGGAAGGTCCACCTCGT,+
3176231,250F302306011_14_5389_13498_240964337_12830_1_...,AGAGTGTCGGGGAAGGCCGCAGAA,-14,9.0,AGAGTAGGTACATCG,-29.0,AAAAA,-57.0,12,NaN,+
3176232,250F302306011_13_4275_10946_220075964_15924_3_...,CGCGAACGGCGGAAGGTATTCCACGT,-17,4.0,ATTTCATGACCATCG,-35.0,AAAAA,-60.0,5,NaN,+
3176233,250F302306011_13_5837_14173_220426086_50586_0_...,TTCGCCTGACGGAAGGGGCTTCCAGG,-17,8.0,TAGTAGGAAGCATCG,-32.0,AAATA,-60.0,5,TTCGCCTGACGGAAGGGCTTCCAGGC,+

In [68]:
import numpy as np 
mask = (test_csv['BC_corrected'].notna()) & (test_csv['BC_corrected'] != '') \
       & (test_csv['putative_umi'].notna()) & (test_csv['putative_umi'] != '')

double_count = mask.sum()
count_tot = test_csv.shape[0]
demul_count_tot = test_csv[(test_csv["BC_corrected"].notna()) & (test_csv["BC_corrected"] != "")].shape[0]

print(f"Number of full length reads: {count_tot}")
print(f"Number of reads with valid barcode: {demul_count_tot}")
print(f"Number of reads with valid barcode and valid umi: {double_count}")
print(f"Proportion of reads with valid barcodes: {np.round(demul_count_tot/count_tot, 3)}")

Number of full length reads: 3176234
Number of reads with valid barcode: 2223981
Number of reads with valid barcode and valid umi: 2104347
Proportion of reads with valid barcodes: 0.7

In [69]:
demul_count_tot

2223981

In [70]:
# 找出 BC_corrected 为空且 putative_bc 有值的行
subset = test_csv[test_csv['BC_corrected'].isna() & test_csv['putative_bc'].notna()]

In [71]:
subset

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,read_types,BC_corrected,strand
4,250F302306011_11_192_9886_196073109_13496_1_16.26,TTGGAATCGGGGAAGGTGGCGAACGT,-16,25.0,ATAGGCTCAACATCG,-31.0,AAAAA,-81.0,1,NaN,+
9,250F302306011_13_5076_9972_221463097_28471_2_1...,ACGGTCTTGCGAAGCGAATTTGGACT,-1,NaN,CAGACATGGCAGTGG,-1014.0,CATGT,NaN,10,NaN,+
13,250F302306011_12_6564_10636_213033515_9619_0_1...,AGAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+
18,250F302306011_11_92_8679_195981433_113125_3_14.94,AAAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,GATAAGGTCGCCATG,-1372.0,ATGTC,-1453.0,9,NaN,+
19,250F302306011_11_136_11421_196073313_21329_3_9.79,TAAAAGACCGCCGGGAAGGAATCCAC,-13,2.0,GAGTTGTGGTCATCG,-31.0,AAAAA,-63.0,12,NaN,+
...,...,...,...,...,...,...,...,...,...,...,...
3176209,250F302306011_13_4575_11951_221090884_15019_1_...,CCGGCCGAAGGGAAGGGCTTGGAGCC,-16,17.0,TCGCCTTTAGCATCG,-31.0,AAAAA,-67.0,1,NaN,+
3176225,250F302306011_13_4326_8770_220079480_11065_2_1...,ACTCTTCACTGGAAGGTCAACTCTGG,-16,11.0,ACCCAACAATCATCG,-31.0,AAAAA,-66.0,1,NaN,+
3176228,250F302306011_13_4297_10538_220073674_17933_2_...,TCACCAGAATGGGGGCAGCAACTATT,-1,NaN,CGGCAACGGTCCAAT,-887.0,ACCCA,NaN,10,NaN,+
3176231,250F302306011_14_5389_13498_240964337_12830_1_...,AGAGTGTCGGGGAAGGCCGCAGAA,-14,9.0,AGAGTAGGTACATCG,-29.0,AAAAA,-57.0,12,NaN,+
3176232,250F302306011_13_4275_10946_220075964_15924_3_...,CGCGAACGGCGGAAGGTATTCCACGT,-17,4.0,ATTTCATGACCATCG,-35.0,AAAAA,-60.0,5,NaN,+

In [72]:
a_ratio = subset['putative_bc'].apply(lambda x: x.count("A") / len(x))

In [75]:
subset_a = subset[a_ratio > 0.5]

In [76]:
subset_a

,read_id,putative_bc,bc_fixed_locs,putative_bc_min_qs,putative_umi,umi_fixed_locs,post_umi_flankings,polyA_starts,read_types,BC_corrected,strand
13,250F302306011_12_6564_10636_213033515_9619_0_1...,AGAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+
18,250F302306011_11_92_8679_195981433_113125_3_14.94,AAAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,GATAAGGTCGCCATG,-1372.0,ATGTC,-1453.0,9,NaN,+
24,250F302306011_12_4412_11706_212852444_9660_0_8.72,TCCTACCAAAAAAAAAAAAAAAAAAA,-1,NaN,CCCTGGCCGTGGGCC,-348.0,GCGCA,NaN,10,NaN,+
39,250F302306011_11_39_11460_196094650_9433_3_12.38,GTGTAAGCTAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+
82,250F302306011_12_5002_11489_207802382_10100_1_...,GCACTAAAAAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+
...,...,...,...,...,...,...,...,...,...,...,...
3176157,250F302306011_13_4224_11865_220070864_8633_1_1...,AAAACGATAAAAAAAAAAAAAAAAAA,-1,NaN,ACAGTGGTACGAGTC,-94.0,TACCG,NaN,10,NaN,+
3176176,250F302306011_13_4267_13546_220031892_30962_1_...,AAAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,GAAGATTTTGAAGAT,-2438.0,ACGAT,NaN,10,NaN,+
3176179,250F302306011_14_5028_7046_236649067_9500_1_14.60,AAAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,GCTGAGCGAGCTGCA,-307.0,ACTAA,NaN,10,NaN,+
3176188,250F302306011_12_6061_11072_201961427_9500_3_1...,AAAAAAAAAAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+
3176190,250F302306011_13_6425_12991_229452091_13106_3_...,CTTTATGAAAAAAAAAAAAAAAAAAA,-1,NaN,NaN,NaN,NaN,NaN,11,NaN,+